name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
        IMAGE_NAME: "mynode:20"
    steps:
        - uses: actions/checkout@v3 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
        - run: docker image build --tag="${IMAGE_NAME}" ./
        - run: echo "Bonjour" >> index.js
        - run: docker container run --rm --mount type=bind,source="$(pwd)"/index.js,target=/app/index.js "${IMAGE_NAME}" npm run lint
        - run: docker container run --rm ${IMAGE_NAME} npm run lint